=== Erickmarquez7/EstructurasDeDatos/practica05BernalErick/Automoviles.dtd
<!--
Archivo de descripción para automoviles XML.
Author: Erick Bernal Márquez, 317042522
Version: 1.0 2020
-->

<!ELEMENT Automoviles (#PCDATA) >
<!ELEMENT Auto (#PCDATA) >
<!ELEMENT Propietario (#PCDATA) >
<!ELEMENT Opinion (#PCDATA) >

<!ATTLIST Auto marca CDATA #REQUIRED >
<!ATTLIST Auto modelo CDATA #REQUIRED >

<!ATTLIST Auto placas CDATA #IMPLIED >
<!ATTLIST Auto anio CDATA #IMPLIED >

<!ATTLIST Propietario nombre CDATA #REQUIRED >
<!ATTLIST Propietario paterno CDATA #REQUIRED >
<!ATTLIST Propietario materno CDATA #REQUIRED >

=== Erickmarquez7/EstructurasDeDatos/practica05BernalErick/Automoviles.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Automoviles SYSTEM "Automoviles.dtd">

<Automoviles>
	<Auto marca="Honda" modelo="Civic" placas="DFS-76-23">
		<Propietario nombre="Pablo" materno="Moreno" paterno="Reyes"/>
		<Opinion>Tiene muy buen rendimiento</Opinion>
	</Auto>
	<Auto marca="BMW" modelo="Serie 2" anio="2014">
		<Propietario nombre="Esteban" materno="Herrera" paterno="Ortega"/>
		<Opinion>Ahorra gasolina</Opinion>
	</Auto>
	<Auto marca="Ford" modelo="Focus" placas="HBZ-87-32" anio="2015">
		<Propietario nombre="Daniela" materno="Torres" paterno="Aguilar"/>
		<Opinion>Es muy practico</Opinion>
	</Auto>
	<Auto marca="Nissan" modelo="X-Trail">
		<Propietario nombre="Laura" materno="Lara" paterno="Fuentes"/>
		<Opinion>Buena distribucion de espacio</Opinion>
	</Auto>
</Automoviles>
